apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vsnet-matchmaker
spec:
  replicas: 5
  template:
    metadata:
      labels:
        role: vsnet-matchmaker
    spec:
      nodeSelector:
        role: apps
      containers:
      - name: vsnet-matchmaker
        image: makeshiftsoftware/vsnet-matchmaker:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        env:
          - name: NODE_ENV
            value: "development"
          - name: PORT
            value: "3000"
          - name: LOG_LEVEL
            value: "debug"
          - name: REDIS_STORE_SERVICE
            value: matchmaker-redis-store:6379
          - name: REDIS_PUBSUB_SERVICE
            value: matchmaker-redis-pubsub:6379
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: secret
                key: app_secret
          - name: REDIS_STORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: matchmaker_redis_store_password
          - name: REDIS_PUBSUB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: matchmaker_redis_pubsub_password