---
apiVersion: v1
kind: Service
metadata:
  name: matchmaker-redis-pubsub
  labels:
    service: matchmaker-redis-pubsub
spec:
  ports:
  - port: 6379
  selector:
    role: matchmaker-redis-pubsub
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: matchmaker-redis-pubsub
spec:
  serviceName: "matchmaker-redis-pubsub"
  replicas: 1
  template:
    metadata:
      labels:
        role: matchmaker-redis-pubsub
    spec:
      nodeSelector:
        role: apps
      terminationGracePeriodSeconds: 10
      containers:
      - name: matchmaker-redis-pubsub
        image: redis:3
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi