---
apiVersion: v1
kind: Service
metadata:
  name: matchmaker-redis-store
  labels:
    service: matchmaker-redis-store
spec:
  ports:
  - port: 6379
  selector:
    role: matchmaker-redis-store
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: matchmaker-redis-store
spec:
  serviceName: "matchmaker-redis-store"
  replicas: 1
  template:
    metadata:
      labels:
        role: matchmaker-redis-store
    spec:
      nodeSelector:
        role: apps
      terminationGracePeriodSeconds: 10
      containers:
      - name: matchmaker-redis-store
        image: redis:3
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi